version: "3.7"
services:
  golang_echo_mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

volumes:
  mongo:
